# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import EditProfile_pb2 as EditProfile__pb2


class EditProfileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EditUserProfile = channel.unary_unary(
                '/EditProfile/EditUserProfile',
                request_serializer=EditProfile__pb2.InputMessage.SerializeToString,
                response_deserializer=EditProfile__pb2.Response.FromString,
                )


class EditProfileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EditUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EditProfileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EditUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.EditUserProfile,
                    request_deserializer=EditProfile__pb2.InputMessage.FromString,
                    response_serializer=EditProfile__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EditProfile', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EditProfile(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EditUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EditProfile/EditUserProfile',
            EditProfile__pb2.InputMessage.SerializeToString,
            EditProfile__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
