# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetJobCondition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GetJobCondition.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15GetJobCondition.proto\"!\n\rCondtionInput\x12\x10\n\x08username\x18\x01 \x01(\t\"Y\n\x0e\x43ondtionOutput\x12\x0c\n\x04work\x18\x01 \x01(\t\x12\x15\n\risPetFriendly\x18\x02 \x01(\x08\x12\x11\n\tstartTime\x18\x03 \x01(\x05\x12\x0f\n\x07\x65ndTime\x18\x04 \x01(\x05\x32K\n\x0fGetJobCondition\x12\x38\n\x13GetUserJobCondition\x12\x0e.CondtionInput\x1a\x0f.CondtionOutput\"\x00\x62\x06proto3'
)




_CONDTIONINPUT = _descriptor.Descriptor(
  name='CondtionInput',
  full_name='CondtionInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='CondtionInput.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=58,
)


_CONDTIONOUTPUT = _descriptor.Descriptor(
  name='CondtionOutput',
  full_name='CondtionOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='work', full_name='CondtionOutput.work', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isPetFriendly', full_name='CondtionOutput.isPetFriendly', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startTime', full_name='CondtionOutput.startTime', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endTime', full_name='CondtionOutput.endTime', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['CondtionInput'] = _CONDTIONINPUT
DESCRIPTOR.message_types_by_name['CondtionOutput'] = _CONDTIONOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CondtionInput = _reflection.GeneratedProtocolMessageType('CondtionInput', (_message.Message,), {
  'DESCRIPTOR' : _CONDTIONINPUT,
  '__module__' : 'GetJobCondition_pb2'
  # @@protoc_insertion_point(class_scope:CondtionInput)
  })
_sym_db.RegisterMessage(CondtionInput)

CondtionOutput = _reflection.GeneratedProtocolMessageType('CondtionOutput', (_message.Message,), {
  'DESCRIPTOR' : _CONDTIONOUTPUT,
  '__module__' : 'GetJobCondition_pb2'
  # @@protoc_insertion_point(class_scope:CondtionOutput)
  })
_sym_db.RegisterMessage(CondtionOutput)



_GETJOBCONDITION = _descriptor.ServiceDescriptor(
  name='GetJobCondition',
  full_name='GetJobCondition',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=151,
  serialized_end=226,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUserJobCondition',
    full_name='GetJobCondition.GetUserJobCondition',
    index=0,
    containing_service=None,
    input_type=_CONDTIONINPUT,
    output_type=_CONDTIONOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETJOBCONDITION)

DESCRIPTOR.services_by_name['GetJobCondition'] = _GETJOBCONDITION

# @@protoc_insertion_point(module_scope)
