# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EditJobCondition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='EditJobCondition.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x45\x64itJobCondition.proto\"n\n\x11\x45\x64itCondtionInput\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04work\x18\x02 \x01(\t\x12\x15\n\risPetFriendly\x18\x03 \x01(\x08\x12\x11\n\tstartTime\x18\x04 \x01(\x05\x12\x0f\n\x07\x65ndTime\x18\x05 \x01(\x05\"5\n\x12\x45\x64itCondtionOutput\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x32U\n\x10\x45\x64itJobCondition\x12\x41\n\x14\x45\x64itUserJobCondition\x12\x12.EditCondtionInput\x1a\x13.EditCondtionOutput\"\x00\x62\x06proto3'
)




_EDITCONDTIONINPUT = _descriptor.Descriptor(
  name='EditCondtionInput',
  full_name='EditCondtionInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='EditCondtionInput.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='work', full_name='EditCondtionInput.work', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isPetFriendly', full_name='EditCondtionInput.isPetFriendly', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startTime', full_name='EditCondtionInput.startTime', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endTime', full_name='EditCondtionInput.endTime', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=136,
)


_EDITCONDTIONOUTPUT = _descriptor.Descriptor(
  name='EditCondtionOutput',
  full_name='EditCondtionOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='EditCondtionOutput.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='EditCondtionOutput.status', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['EditCondtionInput'] = _EDITCONDTIONINPUT
DESCRIPTOR.message_types_by_name['EditCondtionOutput'] = _EDITCONDTIONOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EditCondtionInput = _reflection.GeneratedProtocolMessageType('EditCondtionInput', (_message.Message,), {
  'DESCRIPTOR' : _EDITCONDTIONINPUT,
  '__module__' : 'EditJobCondition_pb2'
  # @@protoc_insertion_point(class_scope:EditCondtionInput)
  })
_sym_db.RegisterMessage(EditCondtionInput)

EditCondtionOutput = _reflection.GeneratedProtocolMessageType('EditCondtionOutput', (_message.Message,), {
  'DESCRIPTOR' : _EDITCONDTIONOUTPUT,
  '__module__' : 'EditJobCondition_pb2'
  # @@protoc_insertion_point(class_scope:EditCondtionOutput)
  })
_sym_db.RegisterMessage(EditCondtionOutput)



_EDITJOBCONDITION = _descriptor.ServiceDescriptor(
  name='EditJobCondition',
  full_name='EditJobCondition',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=193,
  serialized_end=278,
  methods=[
  _descriptor.MethodDescriptor(
    name='EditUserJobCondition',
    full_name='EditJobCondition.EditUserJobCondition',
    index=0,
    containing_service=None,
    input_type=_EDITCONDTIONINPUT,
    output_type=_EDITCONDTIONOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EDITJOBCONDITION)

DESCRIPTOR.services_by_name['EditJobCondition'] = _EDITJOBCONDITION

# @@protoc_insertion_point(module_scope)
