# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import EditJobCondition_pb2 as EditJobCondition__pb2


class EditJobConditionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EditUserJobCondition = channel.unary_unary(
                '/EditJobCondition/EditUserJobCondition',
                request_serializer=EditJobCondition__pb2.EditCondtionInput.SerializeToString,
                response_deserializer=EditJobCondition__pb2.EditCondtionOutput.FromString,
                )


class EditJobConditionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EditUserJobCondition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EditJobConditionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EditUserJobCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.EditUserJobCondition,
                    request_deserializer=EditJobCondition__pb2.EditCondtionInput.FromString,
                    response_serializer=EditJobCondition__pb2.EditCondtionOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EditJobCondition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EditJobCondition(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EditUserJobCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EditJobCondition/EditUserJobCondition',
            EditJobCondition__pb2.EditCondtionInput.SerializeToString,
            EditJobCondition__pb2.EditCondtionOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
